apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mechanoidstore
  labels:
    app:  mongodb
    project: mechanoidstore
    tier: db
spec:
  ports:
  - protocol:  TCP
    port:  27017
    targetPort:  27017
  clusterIP: None
  selector:
    app:  mongodb
    project: mechanoidstore
    tier: db