apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shipping
  namespace: mechanoidstore
  labels: #these labels are deployment labels
    app:  shipping
    project: mechanoidstore
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: #these labels are used to find the pods
      app:  shipping
      project: mechanoidstore
      tier: app
  template:
    metadata:
      labels: #these are pod labels
        app:  shipping
        project: mechanoidstore
        tier: app
    spec:
      containers:
      - name: shipping
        image:  "jashwanth5668/shipping:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name:  shipping