apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397825598:role/eksctl-mechanoidstore-nodegroup-sp-NodeInstanceRole-PNUtgAZGZFRj
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - mechanoidstore-pod-reader
      userarn: arn:aws:iam::767397825598:user/Srimaan
      username: Srimaan
    - groups:
      - mechanoidstore-admin
      userarn: arn:aws:iam::767397825598:user/Ravi
      username: Ravi
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 6cf311de-2625-49d8-b104-499442441e3a