apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cart
  namespace: mechanoidstore
  labels: #these labels are deployment labels
    app:  cart
    project: mechanoidstore
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: #these labels are used to find the pods
      app:  cart
      project: mechanoidstore
      tier: app
  template:
    metadata:
      labels: #these are pod labels
        app:  cart
        project: mechanoidstore
        tier: app
    spec:
      containers:
      - name: cart
        image:  "jashwanth5668/cart:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name:  cart