apiVersion: v1
kind: Service
metadata:
  name:  catalogue
  namespace: mechanoidstore
spec:
  selector:
    app:  catalogue
    project: mechanoidstore
    tier: app
  ports:
  - protocol: TCP
    port:  8080 #service port
    targetPort: 8080 #container port